scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: angular
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: -0.5236 # in radian, -30 degree
        upper_angle: 0.5236  # in radian, 30 degree

    filter2:
      name: box
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: laser
        min_x: -20.0
        max_x: -1.2
        min_y: -30.0
        max_y: 30.0
        min_z: -1.0
        max_z: 1.0

    filter3:
      name: speckle_filter
      type: laser_filters/LaserScanSpeckleFilter
      params:
        filter_type: 0
        max_range: 2.0
        max_range_difference: 0.1
        filter_window: 2
